# هذا الملف يخبر Netlify كيف سيتعامل مع الطلبات

[[redirects]]
  from = "/api/*" # أي طلب يبدأ بـ /api
  to = "https://services.orange.eg/:splat" # اذهب إلى خادم اورانج
  status = 200 # تظاهر بأنك أنت من قمت بالرد (هذا هو سر البروكسي)
  force = true

[[redirects]]
  from = "/api-merida/*" # بروكسي منفصل لـ Merida
  to = "https://api.meridagame.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api-balance/*" # بروكسي منفصل للرصيد
  to = "https://www.orange.eg/:splat"
  status = 200
  force = true
